### ISSUE TITLE
Issue with uploading large datasets

### ISSUE THREAD

**Issue by carderne** [energy-data/energydata.info#169]
Tried to upload a 500 MB geojson file through the (Python) API with this code:

```
import sys
import os
import ckanapi  # https://github.com/ckan/ckanapi
import requests

APIKEY = ''  # get API key from your user page
in_file = 'something.geojson'
ckan = ckanapi.RemoteCKAN('https://energydata.info', apikey=APIKEY)
package_name = 'ecowas-river-network-hydropower'
package = ckan.action.package_show(id=package_name)

extension = os.path.splitext(in_file)[1][1:].upper()
resource_name = os.path.splitext(in_file)[0]
print('Creating "{}" resource'.format(in_file))
r = requests.post('https://energydata.info/api/action/resource_create',
                  data={'package_id': package['id'],
                        'name': resource_name,
                        'description': '',
                        'format': extension,
                        'url': 'upload',  # Needed to pass validation
                        },
                  headers={'Authorization': APIKEY},
                  files=[('upload', open(in_file, 'rb'))])
```

and received the following error:

```
Traceback (most recent call last):
File "/home/chris/.local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
chunked=chunked)
File "/home/chris/.local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/lib/python3.5/http/client.py", line 1107, in request
self._send_request(method, url, body, headers)
File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
self.endheaders(body)
File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
self._send_output(message_body)
File "/usr/lib/python3.5/http/client.py", line 936, in _send_output
self.send(message_body)
File "/usr/lib/python3.5/http/client.py", line 908, in send
self.sock.sendall(data)
File "/usr/lib/python3.5/ssl.py", line 899, in sendall
v = self.send(data[count:])
File "/usr/lib/python3.5/ssl.py", line 869, in send
return self._sslobj.write(data)
File "/usr/lib/python3.5/ssl.py", line 594, in write
return self._sslobj.write(data)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/chris/.local/lib/python3.5/site-packages/requests/adapters.py", line 438, in send
timeout=timeout
File "/home/chris/.local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
_stacktrace=sys.exc_info()[2])
File "/home/chris/.local/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 357, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/home/chris/.local/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
raise value.with_traceback(tb)
File "/home/chris/.local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
chunked=chunked)
File "/home/chris/.local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/lib/python3.5/http/client.py", line 1107, in request
self._send_request(method, url, body, headers)
File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
self.endheaders(body)
File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
self._send_output(message_body)
File "/usr/lib/python3.5/http/client.py", line 936, in _send_output
self.send(message_body)
File "/usr/lib/python3.5/http/client.py", line 908, in send
self.sock.sendall(data)
File "/usr/lib/python3.5/ssl.py", line 899, in sendall
v = self.send(data[count:])
File "/usr/lib/python3.5/ssl.py", line 869, in send
return self._sslobj.write(data)
File "/usr/lib/python3.5/ssl.py", line 594, in write
return self._sslobj.write(data)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(22, 'Invalid argument'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "energydata_ckanapi_ECREEE.py", line 51, in
files=[('upload', open(path, 'rb'))])
File "/home/chris/.local/lib/python3.5/site-packages/requests/api.py", line 112, in post
return request('post', url, data=data, json=json, **kwargs)
File "/home/chris/.local/lib/python3.5/site-packages/requests/api.py", line 58, in request
return session.request(method=method, url=url, **kwargs)
File "/home/chris/.local/lib/python3.5/site-packages/requests/sessions.py", line 518, in request
resp = self.send(prep, **send_kwargs)
File "/home/chris/.local/lib/python3.5/site-packages/requests/sessions.py", line 639, in send
r = adapter.send(request, **kwargs)
File "/home/chris/.local/lib/python3.5/site-packages/requests/adapters.py", line 488, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(22, 'Invalid argument'))
```

**Comment by olafveerman** [comment]
This is due to a new file size limit on geojson files. See #82 for more info.
